### ISSUE TITLE
support for layered deployment

### ISSUE THREAD

**Issue by spinosae** [Azure/iotedgedev#430]
Our team has adopted [layered deployment](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring#layered-deployment) to add edge modules on top of base deployment managed by another team. It is therefore in our interest to build a layered deployment manifest only. Here is a sample from MS docs:
```
{
  "content": {
    "modulesContent": {
      "$edgeAgent": {
        "properties.desired.modules.SimulatedTemperatureSensor": {
          "settings": {
            "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": ""
          },
          "type": "docker",
          "status": "running",
          "restartPolicy": "always",
          "version": "1.0"
        }
      },
      "$edgeHub": {
        "properties.desired.routes.upstream": "FROM /messages/* INTO $upstream"
      },
      "SimulatedTemperatureSensor": {
        "properties.desired": {
          "SendData": true,
          "SendInterval": 5
        }
      }
    }
  }
}
```
This format is not recognized by iotedgedev and would fail to build. Do you have plan to support it in your road map?

**Comment by blackchoey** [comment]
Hi @spinosae You need a full IoT Edge deployment template in order to build your solutions, which tells the tool which module needs to be built.
The layered deployment is very likely to miss these information, so couldn't be used to build your solutions. However, you can always commit this layered deployment to your repo along with the traditional deployment manifest. This won't impact the build process.

**Comment by spinosae** [comment]
> Hi @spinosae You need a full IoT Edge deployment template in order to build your solutions, which tells the tool which module needs to be built.
> The layered deployment may miss these information, so couldn't be used to build your solutions. However, you can always commit this layered deployment to your repo along with the traditional deployment manifest. This won't impact the build process.

@blackchoey Thanks for your reply! Yes I am aware of the limitation you mentioned. The issue is that we don't manage the base (full) deployment and only intend to build our custom modules and deliver a layered deployment manifest. Isn't that the whole point of having layered deployment? i.e. decouple modules from base deployment.

For the time being I wrote a script to merge the layered_deployment_template.json and base_deployment_template.json(an arbitrary version got from another team) , build and split it again to produce the final layered_deployment.json. You can see it's not neat at all. A better solution could definitely integrated into iotedgedev.

On the other hand, I could forget about iotedgedev and just manually code the layered deployment manifest and build the modules with raw docker commands. But then I lose all the goodies offered by iotedgedev.

I feel this feature is going to see more demands once people starts to move to the layered deployment workflow. Hence wanted to know if you have and plan to implement.

**Comment by spinosae** [comment]
By the way, the multi-arch build offered by docker buildx is really neat. Combined with multi-stage build I am able to use a single dockerfile to build debug/release modules for all platforms. Any plans to enable that?

**Comment by blackchoey** [comment]
@spinosae You don't need to merge layered deployment with base deployment in order to build your module. You can have one deployment template with only your module and multiple layered deployment in your solution. So you can build your module with the deployment template, and then deploy your module to different IoT Edge solutions with different layered deployment. You can treat the deployment template as a project file that tells how to build required modules.

Do you have any concerns of creating a deployment template file? The deployment template actually doesn't conflict with layered deployment.

**Comment by blackchoey** [comment]
For the multi-arch build you mentioned, do you have an example for this? It sounds a good idea. If you can share more information, we can investigate on that.
If you already have the dockerfile for multi-arch build, you can reference the same dockerfile in different arch in `module.json`. So you can have only one dockerfile in your solution. Hope this workaround helps.

**Comment by FMauroy** [comment]
Hi, we are also looking into using this deployment approach. When do you think this could be implemented? We'd like to know in order to decide if we wait for it or try to find an alternative.
According to my understanding, it should only be a matter of adding an option in the Azure DevOps pipeline configuration form to have the action runner append the "--layered" parameter to the deployment tool, right?
Thanks!

**Comment by FMauroy** [comment]
FWIW, I replaced the default actions that use "iotedgedev" by a custom script relying on "az iot edge deployment" and it works like a charm. We now have automatic layered deployments from Azure DevOps.
HTH

**Comment by liliankasem** [comment]
+1 it would be great to be able to generate the layered deployment manifest through the tool.

I'm not sure what the guidance is at the moment for how to use layered deployment files that have variables that need to be populated, are there any examples of this scenario?

**Comment by MaxThom** [comment]
Hi,
is it possible to use AzureIotEdge tasks in CI&CD pipeline to deploy a layered deployment manifiest ?

```yaml
- task: AzureIoTEdge@2
    displayName: 'Generate deployment manifest - amd64'
    inputs:
      action: 'Generate deployment manifest'
      templateFilePath: 'EdgeModule/deployment.template.json'
      defaultPlatform: 'amd64'
      deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment-amd64.json'
      validateGeneratedDeploymentManifest: 'true'
      fillRegistryCredential: 'true'
  - task: AzureIoTEdge@2
    displayName: 'Deploy to IoT Edge devices - amd64'
    inputs:
      action: 'Deploy to IoT Edge devices'
      deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment-amd64.json'
      azureSubscription: 'AzureMasterThesis(05bb2fdb-b518-414d-94b2-bfecdcb81b44)'
      iothubname: 'ProjectMir-IotHub'
      deploymentid: '$(System.TeamProject)-telemetrymodule-arm64-deployment'
      priority: '0'
      deviceOption: 'Multiple Devices'
      targetcondition: tags.architecture = 'amd64'
```

**Comment by MaxThom** [comment]
> FWIW, I replaced the default actions that use "iotedgedev" by a custom script relying on "az iot edge deployment" and it works like a charm. We now have automatic layered deployments from Azure DevOps.
> HTH

Do you think you can share your script ?

**Comment by MaxThom** [comment]
I made it work without IotEdge Task for layered deployment. In case anybody comes on this post, here is my solution:

```yaml
- stage: build_image_amd64
  displayName: Build Image Amd64
  dependsOn: unit_test
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - name: platform
      value: amd64
    - name: moduleinfo
      value: ModuleAnalytic/module.json
  jobs:
    - job: build_push_image
      displayName: Build & Push Image
      steps:
        - script: |
            echo "##vso[task.setvariable variable=VERSION_ID]$(cat ./${{ variables.moduleinfo }} | sed 's/.*"version":\ "\(.*\)".*/\1/;t;d')"
            echo "##vso[task.setvariable variable=IMAGE_REPOSITORY]$(cat ./${{ variables.moduleinfo }} | sed 's/.*"repository":\ "\(.*\)".*/\1/;t;d')"
          displayName: Get image information from module.json
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            command: login
            containerRegistry: DockerHub-MaxThom
        - task: Docker@2
          displayName: Build and Push
          inputs:
            command: buildAndPush
            repository: $(IMAGE_REPOSITORY)
            Dockerfile: 'ModuleAnalytic/Dockerfile.${{ variables.platform }}'
            buildContext: .
            tags: |
              $(VERSION_ID)-${{ variables.platform }}
- stage: deploy_image_amd64
  displayName: Deploy Image Amd64
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - name: platform
      value: amd64
    - name: priority
      value: '3'
    - name: deploymentid
      value: moduleanalytic-devops-deployment-amd64
    - name: targetcondition
      value: tags.moduleAnalytic=true and tags.architecture='amd64'
    - name: deploymenttemplate
      value: EdgeModule/layered.deployment.template.json
    - name: moduleinfo
      value: ModuleAnalytic/module.json
  jobs:
    - job: deploy_image
      displayName: Deploy Image      
      steps:
        - script: |
            echo "##vso[task.setvariable variable=IMAGE_REPOSITORY]$(cat ./${{ variables.moduleinfo }} | sed 's/.*"repository":\ "\(.*\)".*/\1/;t;d')"
            echo "##vso[task.setvariable variable=IMAGE_VERSION]$(cat ./${{ variables.moduleinfo }} | sed 's/.*"version":\ "\(.*\)".*/\1/;t;d')"
            echo "##vso[task.setvariable variable=IMAGE_PLATFORM]$(echo ${{ variables.platform }})"
          displayName: Get image information from module.json
        - task: replacetokens@3
          displayName: 'Replace tokens in *.config *.json'
          inputs:
            targetFiles: |
             ${{ variables.deploymenttemplate }}
            verbosity: detailed
            tokenPrefix: '${'
            tokenSuffix: '}'
            keepToken: true
        - script: |
            echo "------------------"
            cat ${{ variables.deploymenttemplate }}
          displayName: Display layered deployment
        - task: AzureCLI@2
          displayName: Azure CLI
          inputs:
            azureSubscription: _your_subscription_
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              write-host '------> Starting deployment.'
              az config set extension.use_dynamic_install=yes_without_prompt
              write-host '------> Deleting previous deployment.'
              az iot edge deployment delete -d ${{ variables.deploymentid }} -n ProjectMir-IotHub --verbose
              write-host '------> Deploying new version.'
              az iot edge deployment create -d ${{ variables.deploymentid }} -n ProjectMir-IotHub --priority ${{ variables.priority }} --content ${{ variables.deploymenttemplate }} --target-condition "${{ variables.targetcondition }}" --layered
              write-host '------> Deployment complete!'
```
and my layered deployment file.
````json
{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired.modules.ModuleAnalytic": {
        "settings": {
          "image": "${IMAGE_REPOSITORY}:${IMAGE_VERSION}-${IMAGE_PLATFORM}",
          "createOptions": ""
        },
        "type": "docker",
        "status": "running",
        "restartPolicy": "always",
        "version": "1.0"
      }
    },
    "$edgeHub": {
      "properties.desired.routes.ModuleAnalyticToUpstream": {
        "priority": 0,
        "route": "From /messages/* INTO $upstream",
        "timeToLiveSecs": 7200
      }
    }
  }
}
```
Ty ! <3 the framework.
