### ISSUE TITLE
A fatal error when building arm32v7

### ISSUE THREAD

**Issue by Bengkel** [Azure/iotedgedev#431]
- iotedgedev Version: 2.1.4
- Python Version: 3.6
- Pip Version: 20.1.1
- Development machine OS Version: Windows 10
- IoT Edge device OS Version: arm32v7

Steps to Reproduce:

**1. Create a custom buildagent based on microsoft/iotedgedev image.** 

_Dockerfile:_
```
FROM microsoft/iotedgedev`
```

**2. Create an  Edge module in VS2019 and push to Azure DevOps Repo.**

_module.json:_
```
{
    "$schema-version": "0.0.1",
    "description": "",
  "image": {
    "repository": "${ACR_ADDRESS}/edgemotormodule",
    "tag": {
      "version": "0.0.1",
      "platforms": {
        "amd64": "./Dockerfile.amd64",
        "amd64.debug": "./Dockerfile.amd64.debug",
        "arm32v7": "./Dockerfile.arm32v7",
        "arm32v7.debug": "./Dockerfile.arm32v7.debug",
        "arm64v8": "./Dockerfile.arm64v8",
        "arm64v8.debug": "./Dockerfile.arm64v8.debug",
        "windows-amd64": "./Dockerfile.windows-amd64"
      }
    },
    "buildOptions": [],
    "contextPath": "./"
  },
    "language": "csharp"
}
```

**3. Build the module using Azure DevOps Pipeline.**

_Step in YAML:_
```
- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    defaultPlatform: 'arm32v7'
    templateFilePath: '$(solutionName).Modules/deployment.template.json'
```

_The output:_

```
Step 4/12 : RUN dotnet restore


 ---> Running in 0d31ac6840c5

A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders


ERROR: The command '/bin/sh -c dotnet restore' returned a non-zero code: 131

##[error]Error: The process '/usr/local/bin/iotedgedev' failed with exit code 1
```

When I change the default platform to **amd64** the step succeeds.
