### ISSUE TITLE
CI&CD: Self-hosted ARM agent

### ISSUE THREAD

**Issue by MaxThom** [Azure/iotedgedev#444]
- iotedgedev Version: latest
- Python Version:  2.7 and 3.x
- Pip Version:  latest on both
- Development machine OS Version: Arm32v7
- IoT Edge device OS Version: Arm32v7

Hi, i'm trying to setup a CI&CD self hosted agent to build my DockerArm image on a rpi4. I have configured a new agent and set it up in agent pool. I installed IotEdgeDev using the manual setup "https://github.com/Azure/iotedgedev/wiki/manual-dev-machine-setup". 
The pipeline work when using micrsoft hosted agent with amd64 image.

When the build runs, It always end up in error and I was not able to resolve my issue. I was thinking to maybe remove all the AzureIotEdge task and simply run a docker build and push to dockerhub and then use the "Generate deployment manifest" and "Deploy to Iot Edge devices" in microsoft hosted agent.

If you have any tips, it will be really appreciated. I'm a fan of all of the framework. <3 

Here is the results of the pipeline :
![image](https://user-images.githubusercontent.com/26239574/103461133-041d0100-4cea-11eb-9cbd-aaf2ff192d6e.png)

Here is my pipeline:

```yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: test 
  displayName: Test
  jobs:
    - job: test
      displayName: Test
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Unit Test module'
          inputs:
            command: 'test'
            projects: '*.Test/*.csproj'
            arguments: '-c $(BuildConfiguration) --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true' #--settings $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings

        - task: DotNetCoreCLI@2
          displayName: Install ReportGenerator tool
          inputs:
            command: custom
            custom: tool
            arguments: install --tool-path . dotnet-reportgenerator-globaltool
        - script: ./reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
          displayName: Create reports

        - task: PublishCodeCoverageResults@1
          displayName: 'Publish code coverage'
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml

- stage: build_image_arm32 
  displayName: Build Image Arm32
  pool:
    name: Default
    demands:
        - agent.name -equals raspberrypi
  jobs:
    - job: build_image
      displayName: Build Image
      steps:
        - script: sudo pip install --upgrade cryptography
        - task: AzureIoTEdge@2
          displayName: 'Build module images - arm32v7'
          inputs:
            action: 'Build module images'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'arm32v7'

        - task: AzureIoTEdge@2
          displayName: 'Push module images - arm32v7'
          inputs:
            action: 'Push module images'
            containerregistrytype: 'Generic Container Registry'
            dockerRegistryConnection: 'DockerHub-MaxThom'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'arm32v7'
            fillRegistryCredential: 'true'

        - task: AzureIoTEdge@2
          displayName: 'Generate deployment manifest - arm32v7'
          inputs:
            action: 'Generate deployment manifest'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'arm32v7'
            deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            validateGeneratedDeploymentManifest: 'true'
            fillRegistryCredential: 'true'

        - task: AzureIoTEdge@2
          displayName: 'Deploy to IoT Edge devices - arm32v7'
          inputs:
            action: 'Deploy to IoT Edge devices'
            deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            azureSubscription: 'AzureMasterThesis(05bb2fdb-b518-414d-94b2-bfecdcb81b44)'
            iothubname: 'ProjectMir-IotHub'
            deploymentid: '$(System.TeamProject)-devops-deployment'
            priority: '0'
            deviceOption: 'Multiple Devices'
            targetcondition: tags.architecture = 'arm32v7'
```

Here is my docker file:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7 AS build-env
WORKDIR /app

COPY ./ModuleTelemetry/*.csproj ./ModuleTelemetry/
COPY ./ModuleTelemetry.IotHub/*.csproj ./ModuleTelemetry.IotHub/
COPY ./ModuleTelemetry.Broker/*.csproj ./ModuleTelemetry.Broker/
COPY ./ModuleTelemetry.Core/*.csproj ./ModuleTelemetry.Core/
RUN dotnet restore ./ModuleTelemetry/ModuleTelemetry.csproj
RUN dotnet restore ./ModuleTelemetry.IotHub/ModuleTelemetry.IotHub.csproj
RUN dotnet restore ./ModuleTelemetry.Broker/ModuleTelemetry.Broker.csproj
RUN dotnet restore ./ModuleTelemetry.Core/ModuleTelemetry.Core.csproj

COPY . ./
RUN dotnet publish ./ModuleTelemetry/ModuleTelemetry.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "ModuleTelemetry.dll"]
```

**Comment by MaxThom** [comment]
So in the end, I builded the image without the iotedgedev using normal task. Here is my pipeline:

The arm part:
```yaml
- stage: build_image_arm32v7
  displayName: Build Image Arm32v7
  dependsOn: unit_test
  pool:
    name: Default
    demands:
      - agent.name -equals raspberrypi
  jobs:
    - job: build_push_image
      displayName: Build & Push Image
      steps:
        - script: |
            pwd
            ls
            printenv
        - script: echo "##vso[task.setvariable variable=VERSION_ID]$(cat ./ModuleTelemetry/module.json | sed 's/.*"version":\ "\(.*\)".*/\1/;t;d')"
          displayName: Get version id
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            command: login
            containerRegistry: DockerHub-MaxThom
        - task: Docker@2
          displayName: Build and Push
          inputs:
            command: buildAndPush
            repository: maxthom/moduletelemetry
            Dockerfile: 'ModuleTelemetry/Dockerfile.arm32v7'
            buildContext: .
            tags: |
              $(VERSION_ID)-arm32v7
- stage: deploy_image_arm32v7
  displayName: Deploy Image Arm32v7
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: EdgeModuleDeployment
  jobs:
    - job: deploy_image
      displayName: Deploy Image      
      steps:
        - task: AzureIoTEdge@2
          displayName: 'Generate deployment manifest - arm32v7'
          inputs:
            action: 'Generate deployment manifest'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'arm32v7'
            deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            validateGeneratedDeploymentManifest: 'true'
            fillRegistryCredential: 'true'
        - script: |
           printenv
           echo ---
           cat $(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json
        - task: AzureIoTEdge@2
          displayName: 'Deploy to IoT Edge devices - arm32v7'
          inputs:
            action: 'Deploy to IoT Edge devices'
            deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            azureSubscription: 'AzureMasterThesis(05bb2fdb-b518-414d-94b2-bfecdcb81b44)'
            iothubname: 'ProjectMir-IotHub'
            deploymentid: '$(System.TeamProject)-telemetrymodule-arm32v7-deployment'
            priority: '0'
            deviceOption: 'Multiple Devices'
            targetcondition: tags.architecture = 'arm32v7'
```

Everything
```yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: unit_test
  displayName: Unit Test
  jobs:
    - job: test
      displayName: Test
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Unit Test module'
          inputs:
            command: 'test'
            projects: '*.Test/*.csproj'
            arguments: '-c $(BuildConfiguration) --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true' #--settings $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings
        - task: DotNetCoreCLI@2
          displayName: Install ReportGenerator tool
          inputs:
            command: custom
            custom: tool
            arguments: install --tool-path . dotnet-reportgenerator-globaltool
        - script: ./reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
          displayName: Create reports
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish code coverage'
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml
- stage: build_image_arm32v7
  displayName: Build Image Arm32v7
  dependsOn: unit_test
  pool:
    name: Default
    demands:
      - agent.name -equals raspberrypi
  jobs:
    - job: build_push_image
      displayName: Build & Push Image
      steps:
        - script: |
            pwd
            ls
            printenv
        - script: echo "##vso[task.setvariable variable=VERSION_ID]$(cat ./ModuleTelemetry/module.json | sed 's/.*"version":\ "\(.*\)".*/\1/;t;d')"
          displayName: Get version id
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            command: login
            containerRegistry: DockerHub-MaxThom
        - task: Docker@2
          displayName: Build and Push
          inputs:
            command: buildAndPush
            repository: maxthom/moduletelemetry
            Dockerfile: 'ModuleTelemetry/Dockerfile.arm32v7'
            buildContext: .
            tags: |
              $(VERSION_ID)-arm32v7
- stage: deploy_image_arm32v7
  displayName: Deploy Image Arm32v7
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: EdgeModuleDeployment
  jobs:
    - job: deploy_image
      displayName: Deploy Image      
      steps:
        - task: AzureIoTEdge@2
          displayName: 'Generate deployment manifest - arm32v7'
          inputs:
            action: 'Generate deployment manifest'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'arm32v7'
            deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            validateGeneratedDeploymentManifest: 'true'
            fillRegistryCredential: 'true'
        - script: |
           printenv
           echo ---
           cat $(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json
        - task: AzureIoTEdge@2
          displayName: 'Deploy to IoT Edge devices - arm32v7'
          inputs:
            action: 'Deploy to IoT Edge devices'
            deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment-arm32v7.json'
            azureSubscription: 'AzureMasterThesis(05bb2fdb-b518-414d-94b2-bfecdcb81b44)'
            iothubname: 'ProjectMir-IotHub'
            deploymentid: '$(System.TeamProject)-telemetrymodule-arm32v7-deployment'
            priority: '0'
            deviceOption: 'Multiple Devices'
            targetcondition: tags.architecture = 'arm32v7'
- stage: build_image_amd64
  displayName: Build Image Amd64
  dependsOn: unit_test
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: build_push_image
      displayName: Build & Push Image
      steps:
        - task: AzureIoTEdge@2
          displayName: 'Build module image - amd64'
          inputs:
            action: 'Build module images'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'amd64'        
        - task: AzureIoTEdge@2
          displayName: 'Push module image - amd64'
          inputs:
            action: 'Push module images'
            containerregistrytype: 'Generic Container Registry'
            dockerRegistryConnection: 'DockerHub-MaxThom'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'amd64'
            fillRegistryCredential: 'true'
- stage: deploy_image_amd64
  displayName: Deploy Image Amd64
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: EdgeModuleDeployment
  jobs:
    - job: deploy_image
      displayName: Deploy Image
      steps:
        - task: AzureIoTEdge@2
          displayName: 'Generate deployment manifest - amd64'
          inputs:
            action: 'Generate deployment manifest'
            templateFilePath: 'EdgeModule/deployment.template.json'
            defaultPlatform: 'amd64'
            deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment-amd64.json'
            validateGeneratedDeploymentManifest: 'true'
            fillRegistryCredential: 'true'
        - script: |
           printenv
           echo ---
           cat $(System.DefaultWorkingDirectory)/config/deployment-amd64.json
        - task: AzureIoTEdge@2
          displayName: 'Deploy to IoT Edge devices - amd64'
          inputs:
            action: 'Deploy to IoT Edge devices'
            deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment-amd64.json'
            azureSubscription: 'AzureMasterThesis(05bb2fdb-b518-414d-94b2-bfecdcb81b44)'
            iothubname: 'ProjectMir-IotHub'
            deploymentid: '$(System.TeamProject)-telemetrymodule-arm64-deployment'
            priority: '0'
            deviceOption: 'Multiple Devices'
            targetcondition: tags.architecture = 'amd64'
```
