### ISSUE TITLE
Layered Deployment

### ISSUE THREAD

**Issue by MaxThom** [Azure/iotedgedev#463]
Hi,
we decided to switch to Layered Deployment because we have 4 modules.  I'm using AzureDevOps as CI&CD.
The issue is each time I update one module, it's module twin is reset. There is no update Task similar to the one for normal deployment. So I must use the cli, delete the previous deployment and create a new one with my template. I guess this is why the module is reset, because of the delete ? So how can I update my layered deployment without resetting the module twin ?

Thank you !

Here is the ```layered.deployment.template.json```:
```json
{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired.modules.SenseAI_TelemetrySwarm": {
        "settings": {
          "image": "${IMAGE_REPOSITORY}:${IMAGE_VERSION}-${IMAGE_PLATFORM}",
          "createOptions": ""
        },
        "type": "docker",
        "status": "running",
        "restartPolicy": "always",
        "version": "1.0"
      }
    },
    "$edgeHub": {
      "properties.desired.routes.AllTelemetryToAgentModule": {
        "priority": 0,
        "route": "FROM /messages/modules/SenseAI_TelemetrySwarm/outputs/* WHERE type = 'telemetry' INTO BrokeredEndpoint(\"/modules/SenseAI_TelemetryAgent/inputs/telemetryInput\")",
        "timeToLiveSecs": 7200
      }
    }
  }
}
```

Here is the pipeline section for update:
```yaml
- task: AzureCLI@2
          displayName: Deploy to IoT Edge devices
          inputs:
            azureSubscription: ${{ parameters.azuresubscription }}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              write-host '------> Starting deployment.'
              az config set extension.use_dynamic_install=yes_without_prompt
              write-host '------> Deleting previous deployment.'
              az iot edge deployment delete -d ${{ parameters.deploymentid }} -n ${{ parameters.iothubname }} --verbose
              write-host '------> Deploying new version.'
              start-sleep -seconds 10
              az iot edge deployment create -d ${{ parameters.deploymentid }} -n ${{ parameters.iothubname }} --priority ${{ parameters.priority }} --content ${{ parameters.deploymenttemplate }} --target-condition "${{ parameters.targetcondition }}" --layered
              write-host '------> Deployment complete!'
```

Here is my full pipeline for template filling and deployment:
```yaml
parameters:
  platform: ''
  deploymentid: ''
  priority: ''
  targetcondition: ''
  deploymenttemplate: ''
  moduleinfo: ''
  azuresubscription: ''
  iothubname: ''
jobs:
    - job: deploy_image
      displayName: Deploy Image      
      steps:
        - task: CmdLine@2
          displayName: Get image information from module
          inputs:
            script: |
              echo "##vso[task.setvariable variable=IMAGE_REPOSITORY]$(cat ./${{ parameters.moduleinfo }} | sed 's/.*"repository":\ "\(.*\)".*/\1/;t;d')"
              echo "##vso[task.setvariable variable=IMAGE_VERSION]$(cat ./${{ parameters.moduleinfo }} | sed 's/.*"version":\ "\(.*\)".*/\1.$(Build.BuildId)/;t;d')"
              echo "##vso[task.setvariable variable=IMAGE_PLATFORM]$(echo ${{ parameters.platform }})"
        - task: replacetokens@3
          displayName: 'Replace tokens in deployment template'
          inputs:
            targetFiles: |
             ${{ parameters.deploymenttemplate }}
            verbosity: detailed
            tokenPrefix: '${'
            tokenSuffix: '}'
            keepToken: true
        - script: |
            echo "------------------"
            cat ${{ parameters.deploymenttemplate }}
          displayName: Display layered deployment
        - task: AzureCLI@2
          displayName: Deploy to IoT Edge devices
          inputs:
            azureSubscription: ${{ parameters.azuresubscription }}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              write-host '------> Starting deployment.'
              az config set extension.use_dynamic_install=yes_without_prompt
              write-host '------> Deleting previous deployment.'
              az iot edge deployment delete -d ${{ parameters.deploymentid }} -n ${{ parameters.iothubname }} --verbose
              write-host '------> Deploying new version.'
              start-sleep -seconds 10
              az iot edge deployment create -d ${{ parameters.deploymentid }} -n ${{ parameters.iothubname }} --priority ${{ parameters.priority }} --content ${{ parameters.deploymenttemplate }} --target-condition "${{ parameters.targetcondition }}" --layered
              write-host '------> Deployment complete!'
```
